appName: emailservice
appImage: 245729138833.dkr.ecr.eu-west-3.amazonaws.com/microservices
appVersion: emailservice
appReplicas: 1
containerPort: 8080
containerEntVars:
- name: PORT
  value: "8080"
imagePullSecrets:
- name: regcred

servicePort: 5000
serviceType: ClusterIP